-- Limpia todas las tablas para re-ejecutar la migración
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE planes;
TRUNCATE emisores;
TRUNCATE emisor_suscripciones;
TRUNCATE establecimientos;
TRUNCATE pto_emisiones;
TRUNCATE roles;
TRUNCATE users;
TRUNCATE clientes;
TRUNCATE productos;
TRUNCATE facturas;
TRUNCATE factura_detalles;
TRUNCATE factura_reembolsos;
TRUNCATE nota_creditos;
TRUNCATE nota_credito_detalles;
TRUNCATE nota_debitos;
TRUNCATE nota_debito_motivos;
TRUNCATE retenciones;
TRUNCATE retencion_impuestos;
TRUNCATE retencion_ats;
TRUNCATE doc_sustento_retenciones;
TRUNCATE desgloce_retenciones;
TRUNCATE guias;
TRUNCATE guia_detalles;
TRUNCATE liquidacion_compras;
TRUNCATE liquidacion_detalles;
TRUNCATE proformas;
TRUNCATE proforma_detalles;
TRUNCATE compras;
TRUNCATE compra_detalles;
TRUNCATE impuestos;
TRUNCATE campos_adicionales;
TRUNCATE mensajes;
TRUNCATE impuesto_ivas;
TRUNCATE impuesto_ices;
TRUNCATE impuesto_irbpnrs;
SET FOREIGN_KEY_CHECKS = 1;
SELECT 'Todas las tablas truncadas' AS resultado;
